[web]
web-1 ansible_host=111.88.250.22 fqdn=fhmo14b8geuiat6vsme7.auto.internal
web-2 ansible_host=89.169.156.108 fqdn=fhm20un8qn0s0j7kiddf.auto.internal

[db]
main ansible_host=62.84.116.49 fqdn=fhmrmgj384rit933jo4i.auto.internal
replica ansible_host=93.77.180.0 fqdn=fhm3t7fuk2pvqu6t7uis.auto.internal

[storage]
storage ansible_host=89.169.156.26 fqdn=fhmnnc05hfoko0tjsbl6.auto.internal
